#INCLUDE <16F876.H>
#FUSES   XT,NOWDT
#USE  DELAY(CLOCK=4000000)
#USE  RS232(BAUD=9600,XMIT=PIN_C6,RCV=PIN_C7)
#INCLUDE <FLEXLCD.H>

VOID MAIN(){
INT VALOR;
LCD_INIT();

WHILE(TRUE){
   FOR(VALOR=0;VALOR<=10;VALOR++){
   PUTC(VALOR);
   PRINTF(LCD_PUTC,"\fEnviando= %1d",VALOR);
   DELAY_MS(500);
   }
}
}
